---
- name: Deploy Auction System to Minikube
  hosts: local
  connection: local
  gather_facts: false
  vars:
    namespace: auction-system
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vault/secrets.yml
  tasks:
   
    - name: Create Namespace
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '/home/ankur/SPE/real-time-auction-system/devops/k8s/backend/namespace.yml') | from_yaml }}"
        # definition: "{{ lookup('file', '../../../k8s/backend/namespace.yml') | from_yaml }}"

    - name: Create JWT Secret for all services
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: jwt-secret
            namespace: "{{ namespace }}"
          type: Opaque
          stringData:
            jwt-secret: "{{ vault_jwt_secret }}"

    - name: Create Auth DB Secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: auth-service-secrets
            namespace: "{{ namespace }}"
          type: Opaque
          stringData:
            datasource-url: "jdbc:mysql://mysql-auth-svc:3306/auction_auth_db"
            datasource-username: "{{ vault_auth_db_user }}"
            datasource-password: "{{ vault_auth_db_pass }}"
            jwt-secret: "{{ vault_jwt_secret }}"

    - name: Create Auction DB Secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: auction-service-secrets
            namespace: "{{ namespace }}"
          type: Opaque
          stringData:
            datasource-url: "jdbc:mysql://mysql-auction-svc:3306/auction_db"
            datasource-username: "{{ vault_auction_db_user }}"
            datasource-password: "{{ vault_auction_db_pass }}"

    - name: Create Bidding DB Secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: bidding-service-secrets
            namespace: "{{ namespace }}"
          type: Opaque
          stringData:
            datasource-url: "jdbc:mysql://mysql-bidding-svc:3306/auction_bidding_db"
            datasource-username: "{{ vault_bidding_db_user }}"
            datasource-password: "{{ vault_bidding_db_pass }}"

    - name: Apply all Kubernetes manifests
      kubernetes.core.k8s:
        state: present
        src: "{{ item }}"
      loop:
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/mysql-auth.yml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/mysql-auction.yml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/mysql-bidding.yml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/eureka-server-service/deployment.yaml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/auth-service/deployment.yaml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/auth-service/hpa.yaml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/auction-service/deployment.yaml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/auction-service/hpa.yaml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/bidding-service/deployment.yaml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/bidding-service/hpa.yaml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/api-gateway-service/deployment.yaml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/api-gateway-service/hpa.yaml
        - /home/ankur/SPE/real-time-auction-system/devops/k8s/backend/api-gateway-service/ingress.yaml
    

  
  

