# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-bidding-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-bidding
spec:
  selector:
    matchLabels:
      app: mysql-bidding
  template:
    metadata:
      labels:
        app: mysql-bidding
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bidding-service-secrets
                  key: datasource-password
            - name: MYSQL_DATABASE
              value: auction_bidding_db
            - name: MYSQL_USER
              value: ankur
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bidding-service-secrets
                  key: datasource-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-bidding-pvc
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-bidding
spec:
  selector:
    app: mysql-bidding
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
