logging:
  config: classpath:logback-spring.xml
  level:
    com.auction_system: DEBUG
    org.springframework.boot.actuate: INFO

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"         
  endpoint:
    health:
      show-details: always    
      probes:
        enabled: true

server:
  port: 8084

spring:
  application:
    name: bidding-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    # url: jdbc:mysql://mysql-bidding-svc:3306/auction_bidding_db?createDatabaseIfNotExist=true
    # url: jdbc:mysql://localhost:3306/auction_bidding_db?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME}
    # username: ankur
    password: ${SPRING_DATASOURCE_PASSWORD}
    # password: Ankur@2k24
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}
      # defaultZone: http://eureka-server:8761/eureka/
#      defaultZone: http://eureka-server.auction-system.svc.cluster.local:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true
