server:
  port: 8084

spring:
  application:
    name: bidding-service
  datasource:
    url: jdbc:mysql://mysql-bidding.auction-system.svc.cluster.local:3306/auction_bidding_db?createDatabaseIfNotExist=true
    username: ankur
    password: Ankur@2k24
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server.auction-system.svc.cluster.local:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

logging:
  level:
    com.auction_system: DEBUG
