apiVersion: apps/v1
kind: Deployment
metadata: 
  name: eureka-server
  namespace: auction-system 
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: eureka-server 
  template:
    metadata:  
      labels: 
        app: eureka-server 
    spec:
      containers:
      - name: eureka-server
        image: ankur2k19/eureka-server:latest
        ports: [{ containerPort: 8761, name: eureka }]
      
---
apiVersion: v1
kind: Service
metadata: 
  name: eureka-server
  namespace: auction-system 
spec:
  selector: 
    app: eureka-server 
  ports: [{ port: 8761, targetPort: 8761, name: eureka }]
