---
- name: Deploy frontend dev to Minikube
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Apply Kubernetes manifests
      shell: |
        cd k8s/
        kubectl delete -f . --ignore-not-found
        kubectl apply -f .

