---
- name: Deploy frontend dev to Minikube
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: Create namespace
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: auction-system

    - name: Apply Kubernetes manifests
      shell: |
        cd k8s/
        kubectl delete -f . --ignore-not-found
        kubectl apply -f .

    # - name: Apply Frontend Service
    #   kubernetes.core.k8s:
    #     state: present
    #     src: ../k8s/frontend-service.yml
    #     namespace: auction-system

    # - name: Apply Frontend Ingress (Optional)
    #   kubernetes.core.k8s:
    #     state: present
    #     src: ../k8s/frontend-ingress.yml
    #     namespace: auction-system

