pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = 'auction-system-frontend'
        GITHUB_REPO_URL = 'https://github.com/Ankur7470/real-time-auction-system.git'
    }

    triggers {
        githubPush()
    }

    stages {
         stage('Checkout') {
            steps {
                script {
                    git branch: 'main', url: "${GITHUB_REPO_URL}"
                }
            }
        }

        stage('Detect Frontend Changes') {
            steps {
                script {
                    def changes = sh(script: "git diff --name-only HEAD~1 HEAD | grep '^frontend/' || true", returnStdout: true).trim()
                    if (changes == "") {
                        echo "No changes in frontend folder. Skipping pipeline."
                        currentBuild.result = 'SUCCESS'
                        currentBuild.description = "No frontend changes"
                        error("No frontend changes")
                    }
                }
            }
        }

        stage('Build Frontend Docker Image') {
            steps {
                dir('frontend') {
                    sh "docker build -t $DOCKER_IMAGE_NAME:${env.BUILD_NUMBER} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('', 'DockerHubCred') {
                        sh "docker tag $DOCKER_IMAGE_NAME:${env.BUILD_NUMBER} ankur2k19/$DOCKER_IMAGE_NAME:latest"
                        sh "docker push ankur2k19/$DOCKER_IMAGE_NAME:${env.BUILD_NUMBER}"
                        sh "docker push ankur2k19/$DOCKER_IMAGE_NAME:latest"

                    }
                }

            }
        }
    }
}