apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: auction-system
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: api-gateway 
  template:
    metadata: 
      labels: 
        app: api-gateway 
    spec:
      initContainers:
      - name: wait-for-eureka
        image: busybox
        command:
          - sh
          - -c
          - until nc -z eureka-server 8761; do echo "Waiting for Eureka server"; sleep 5; done
      containers:
      - name: api-gateway
        image: ankur2k19/api-gateway:latest
        imagePullPolicy: Always
        ports: 
        - containerPort: 8000
          name: http
        env:
        - name: EUREKA_SERVER_URI
          value: http://eureka-server:8761/eureka/
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef: 
              name: jwt-secret
              key: jwt-secret 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8761
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
      
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  namespace: auction-system
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 31001  

