logging:
  config: classpath:logback-spring.xml
  level:
    # org.springframework.security: DEBUG
    com.auction_system: DEBUG
    org.springframework.boot.actuate: INFO

# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
#   endpoint:
#     health:
#       show-details: always
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"          # Exposes all actuator endpoints including health
  endpoint:
    health:
      show-details: always    # Optional: shows full health info
      probes:
        enabled: true

server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql-auth-svc:3306/auction_auth_db?createDatabaseIfNotExist=true
    # url: jdbc:mysql://localhost:3306/auction_auth_db?createDatabaseIfNotExist=true
#    username: ${SPRING_DATASOURCE_USERNAME}
    username: ankur
#    password: ${SPRING_DATASOURCE_PASSWORD}
    password: Ankur@2k24
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#      defaultZone: http://eureka-server.auction-system.svc.cluster.local:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

jwt:
#  secret: ${JWT_SECRET}
  secret: auctionSecretKey123456789012345678901234567890
  expirationMs: 86400000
