apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-service
  namespace: auction-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bidding-service       # ← required
  template:
    metadata:
      labels:
        app: bidding-service     # ← must match selector
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command:
          - sh
          - -c
          - until nc -z mysql-bidding-svc 3306; do echo "Waiting for DB"; sleep 2; done
      containers:
      - name: bidding-service
        image: ankur2k19/bidding-service:latest
        ports:
          - containerPort: 8084
            name: http
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: bidding-service-secrets
                key: datasource-url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: bidding-service-secrets
                key: datasource-username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bidding-service-secrets
                key: datasource-password

---
apiVersion: v1
kind: Service
metadata:
  name: bidding-service
  namespace: auction-system
spec:
  selector:
    app: bidding-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084