apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-service
  namespace: auction-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bidding-service
  template:
    metadata:
      labels:
        app: bidding-service
    spec:
      containers:
        - name: bidding-service
          image: ankur2k19/bidding-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: bidding-service-secrets
                  key: datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bidding-service-secrets
                  key: datasource-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bidding-service-secrets
                  key: datasource-password
---
apiVersion: v1
kind: Service
metadata:
  name: bidding-service
spec:
  selector:
    app: bidding-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
