apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bid-service-hpa
  namespace: auction-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bidding-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
