apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: auction-system
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80           # Service listens on port 80
      targetPort: 80     # Container listens on port 80 (as set in Dockerfile)
      nodePort: 31000    # Fixed NodePort for Minikube
