apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: auction-system  
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: auction-frontend
          image: ankur2k19/auction-system-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          # env:
          #   - name: VITE_API_URL
          #     value: "http://api-gateway-svc.auction-system.svc.cluster.local"
