server:
  port: 8761

logging:
  config: classpath:logback-spring.xml
  level:
    com.auction_system: DEBUG
    org.springframework.boot.actuate: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: eureka-server
  freemarker:
    template-loader-path: classpath:/templates/

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 60000
    wait-time-in-ms-when-sync-empty: 5
