apiVersion: apps/v1
kind: Deployment
metadata: { name: auth-service, namespace: auction-system }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql-auth-svc 3306; do echo "Waiting for DB"; sleep 2; done']
      containers:
      - name: auth-service
        image: ankur2k19/auth-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: datasource-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: datasource-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: datasource-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-service-secrets
              key: jwt-secret

---
# apiVersion: v1
# kind: Service
# metadata: { name: auth-service, namespace: auction-system }
# spec:
#   selector: { app: auth-service }
#   ports: [{ port: 8082, targetPort: 8082 }]
#   type: ClusterIP

# Example for auth-service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auction-system
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
