server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: auction-service
          uri: lb://auction-service
          predicates:
            - Path=/api/auctions/**
        - id: bidding-service
          uri: lb://bidding-service
          predicates:
            - Path=/api/bids/**
        - id: bidding-service-ws
          uri: lb://bidding-service
          predicates:
            - Path=/ws-auction/**
          metadata:
            protocol: ws
      httpclient:
        websocket:
          max-frame-payload-length: 65536

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"          
  endpoint:
    health:
      show-details: always  
      probes:
        enabled: true

logging:
  config: classpath:logback-spring.xml
  level:
    com.auction_system: DEBUG
    org.springframework.boot.actuate: INFO

