- name: Deploy frontend to Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Apply frontend deployment
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        src: ../k8s/frontend-deployment.yaml
