apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-frontend
  labels:
    app: auction-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auction-frontend
  template:
    metadata:
      labels:
        app: auction-frontend
    spec:
      containers:
      - name: auction-frontend
        image: ankur2k19/auction-system-frontend:latest
        ports:
        - containerPort: 80
