logging:
  config: classpath:logback-spring.xml
  level:
    # org.springframework.security: DEBUG
    com.auction_system: DEBUG
    org.springframework.boot.actuate: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8083

spring:
  application:
    name: auction-service
  datasource:
    url: jdbc:mysql://mysql-auction-svc:3306/auction_db?createDatabaseIfNotExist=true
    # url: jdbc:mysql://localhost:3306/auction_service_db?createDatabaseIfNotExist=true
#    username: ${SPRING_DATASOURCE_USERNAME}
    username: ankur
#    password: ${SPRING_DATASOURCE_PASSWORD}
    password: Ankur@2k24
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#      defaultZone: http://eureka-server.auction-system.svc.cluster.local:8761/eureka/
      # defaultZOne: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true
