- name: Create JWT secret
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: jwt-secret
        namespace: auction-system
      type: Opaque
      data:
        jwt-secret: "{{ vault_jwt_secret | b64encode }}"

- name: Create DB secrets
  block:
    - name: Auth DB secret
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: auth-service-secrets
            namespace: auction-system
          type: Opaque
          data:
            datasource-url: "{{ auth_datasource_url | b64encode }}"
            datasource-username: "{{ 'ankur' | b64encode }}"
            datasource-password: "{{ vault_mysql_auth_password | b64encode }}"
            jwt-secret: "{{ vault_jwt_secret | b64encode }}"

    - name: Auction DB secret
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: auction-service-secrets
            namespace: auction-system
          type: Opaque
          data:
            datasource-url: "{{ auction_datasource_url | b64encode }}"
            datasource-username: "{{ 'ankur' | b64encode }}"
            datasource-password: "{{ vault_mysql_auction_password | b64encode }}"

    - name: Bidding DB secret
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: bidding-service-secrets
            namespace: auction-system
          type: Opaque
          data:
            datasource-url: "{{ bidding_datasource_url | b64encode }}"
            datasource-username: "{{ 'ankur' | b64encode }}"
            datasource-password: "{{ vault_mysql_bidding_password | b64encode }}"

    - name: API Gateway JWT secret
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: api-gateway-secrets
            namespace: auction-system
          type: Opaque
          data:
            jwt-secret: "{{ vault_jwt_secret | b64encode }}"
