# ---
# - name: Deploy API Gateway
#   kubernetes.core.k8s:
#     kubeconfig: ~/.kube/config
#     state: present
#     src: ../k8s/api-gateway-service/deployment.yaml
#     namespace: auction-system

# - name: Deploy Auth Service
#   kubernetes.core.k8s:
#     kubeconfig: ~/.kube/config
#     state: present
#     src: ../k8s/auth-service/deployment.yaml
#     namespace: auction-system

# - name: Deploy Auction Service
#   kubernetes.core.k8s:
#     kubeconfig: ~/.kube/config
#     state: present
#     src: ../k8s/auction-service/deployment.yaml
#     namespace: auction-system

# - name: Deploy Bidding Service
#   kubernetes.core.k8s:
#     kubeconfig: ~/.kube/config
#     state: present
#     src: ../k8s/bidding-service/deployment.yaml
#     namespace: auction-system

# # Optional HPA block (add kubeconfig if enabling it)
# # - name: Deploy HPA for services
# #   block:
# #     - name: API Gateway HPA
# #       kubernetes.core.k8s:
# #         kubeconfig: ~/.kube/config
# #         state: present
# #         src: ../k8s/api-gateway-service/hpa.yml
# #         namespace: auction-system
# #     - name: Auth Service HPA
# #       kubernetes.core.k8s:
# #         kubeconfig: ~/.kube/config
# #         state: present
# #         src: ../k8s/auth-service/hpa.yaml
# #         namespace: auction-system
# #   when: "'autoscale' in ansible_run_tags"

# - name: Verify deployments
#   kubernetes.core.k8s_info:
#     kubeconfig: ~/.kube/config
#     kind: Deployment
#     namespace: auction-system
#   register: deployments

# - debug:
#     msg: "Current deployments: {{ deployments.resources | map(attribute='metadata.name') | list }}"
