---
- name: Ensure kubectl is configured
  command: kubectl cluster-info
  register: kube_check
  failed_when: kube_check.rc != 0
  changed_when: false

- name: Create namespace
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: auction-system

- name: Create all secrets
  include_tasks: create-secrets.yml

- name: Deploy databases
  block:
    - name: Deploy MySQL for Auth
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../k8s/mysql-auth.yml
        namespace: auction-system

    - name: Deploy MySQL for Auction
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../k8s/mysql-auction.yml
        namespace: auction-system

    - name: Deploy MySQL for Bidding
      kubernetes.core.k8s:
        kubeconfig: ~/.kube/config
        state: present
        src: ../k8s/mysql-bidding.yml
        namespace: auction-system
  when: "'database' in ansible_run_tags"

- name: Deploy Eureka Server
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    state: present
    src: ../k8s/eureka-server-service/deployment.yaml
    namespace: auction-system

- name: Wait for Eureka to be ready
  kubernetes.core.k8s_info:
    kubeconfig: ~/.kube/config
    kind: Pod
    namespace: auction-system
    label_selectors:
      - app = eureka-server
    wait: yes
    wait_timeout: 120

- name: Deploy all microservices
  include_tasks: deploy-services.yml
