apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-service
  namespace: auction-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-service       
  template:
    metadata:
      labels:
        app: auction-service     
    spec:
      initContainers:
      - name: wait-for-eureka
        image: busybox
        command:
          - sh
          - -c
          - until nc -z eureka-server 8761; do echo "Waiting for Eureka server"; sleep 5; done
      - name: wait-for-db
        image: busybox
        command:
          - sh
          - -c
          - until nc -z mysql-auction-0.mysql-auction-svc 3306; do echo "Waiting for DB"; sleep 2; done
      containers:
      - name: auction-service
        image: ankur2k19/auction-service:latest
        ports:
          - containerPort: 8083
            name: http
        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: auction-service-secrets
                key: datasource-url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: auction-service-secrets
                key: datasource-username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auction-service-secrets
                key: datasource-password
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8761
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # resources:
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: auction-service
  namespace: auction-system
spec:
  selector:
    app: auction-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
